// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL-Avo1oHd1CWsAK6LxnwR5ZYWn1-X3FM',
    appId: '1:158080734738:web:93f5a583bf75f07258eacb',
    messagingSenderId: '158080734738',
    projectId: 'login-bdf50',
    authDomain: 'login-bdf50.firebaseapp.com',
    storageBucket: 'login-bdf50.appspot.com',
    measurementId: 'G-7G3V49844W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV1YPKSCIALqaSuTkfMPBSItQI5znjJ5s',
    appId: '1:158080734738:android:f1cfcba07a58440458eacb',
    messagingSenderId: '158080734738',
    projectId: 'login-bdf50',
    storageBucket: 'login-bdf50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDvEoJCF2dsHsCvIb5-t4EyQ8xFQcYA-Q',
    appId: '1:158080734738:ios:9a02497ba39f179058eacb',
    messagingSenderId: '158080734738',
    projectId: 'login-bdf50',
    storageBucket: 'login-bdf50.appspot.com',
    iosClientId: '158080734738-rprfp2meqp5m1lt546lc1korfgaeiuhs.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDvEoJCF2dsHsCvIb5-t4EyQ8xFQcYA-Q',
    appId: '1:158080734738:ios:9a02497ba39f179058eacb',
    messagingSenderId: '158080734738',
    projectId: 'login-bdf50',
    storageBucket: 'login-bdf50.appspot.com',
    iosClientId: '158080734738-rprfp2meqp5m1lt546lc1korfgaeiuhs.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginSystem',
  );
}
